# Generated by Django 3.2 on 2022-05-13 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20220512_2357'),
        ('Personal_Room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailywork',
            name='room',
        ),
        migrations.AddField(
            model_name='dailywork',
            name='renter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.renter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailywork',
            name='task',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
