# Generated by Django 3.2.1 on 2022-05-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('room_number', models.IntegerField()),
                ('capacity', models.FloatField()),
            ],
        ),
    ]
