# Generated by Django 3.2.1 on 2022-05-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.CharField(max_length=20),
        ),
    ]
