# Generated by Django 3.2 on 2022-05-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_alter_room_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='capacity',
            new_name='area',
        ),
        migrations.AddField(
            model_name='room',
            name='room_price',
            field=models.FloatField(default=0),
        ),
    ]
