# Generated by Django 3.2 on 2022-05-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0003_auto_20220512_2313'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(check=models.Q(room_number__gte=0), name='s'),
        ),
    ]
