# Generated by Django 3.2 on 2022-05-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0006_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='desciption',
            field=models.CharField(default='', max_length=250),
        ),
    ]
