# Generated by Django 3.2 on 2022-05-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0007_room_desciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='desciption',
            new_name='description',
        ),
    ]
