# Generated by Django 3.2 on 2022-05-13 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0004_bill_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='room_fee',
        ),
    ]
