# Generated by Django 3.2 on 2022-05-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0005_remove_bill_room_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
