# Generated by Django 3.2 on 2022-05-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0007_auto_20220531_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='pay_status',
            field=models.BooleanField(default=False),
        ),
    ]
