# Generated by Django 3.2 on 2022-06-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0008_bill_pay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(),
        ),
    ]
