# Generated by Django 3.1.1 on 2023-05-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed_Back', '0002_feedback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
