# Generated by Django 3.2 on 2022-05-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20220512_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_numer',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
