# Generated by Django 3.2 on 2022-05-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_renter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
